# Generated by Django 4.2.6 on 2023-10-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='message',
            field=models.CharField(),
        ),
    ]
